### PR TITLE
refactor(full frontend): bring over files from MEC and strip out ever…

### PR DESCRIPTION
**Pull request by willcbelcher**
…ything except basic blocks

All frontend files were brought over from MEC. All components except the header and footer were
removed, and only the home and 404 views were kept. This will allow us to start building the layout
of the app from scratch components while having the basic building blocks of the app already there.

BREAKING CHANGE: frontend completely changed but runs

4

### CODE REVIEW

**Review by jdhaines — CHANGES_REQUESTED** [review]
Recommend you go through all these files and try to understand what they do. The frontend unit tests shouldn't be brought over unless they make sense. Same with integration tests. Changelog doest make sense, and the package.json still says Mec.   Bringing files over should be a copy then understand/modify.

**Comment by willcbelcher** [comment]
I took a second look through all the files and updated what I noticed, plus the updates from above. Certainly possible I missed something though, so I'm glad we have these review processes.

**Review by jdhaines — CHANGES_REQUESTED** [review]
`package.json` has metrics spelled wrong.  :)

**Review by jdhaines — APPROVED** [review]
LGTM

**Pull request merged**
